services:
  app:
    build: .
    container_name: developer_scrape
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - redis
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - 6379:6379
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome_driver
    ports:
      - 4444:4444
    hostname: chrome
    privileged: true
    shm_size: 2g