"""empty message

Revision ID: 401c6999e9fb
Revises: e7d44338d4a9
Create Date: 2023-03-17 14:38:13.253491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401c6999e9fb'
down_revision = 'e7d44338d4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
