"""empty message

Revision ID: e7d44338d4a9
Revises: 
Create Date: 2023-03-14 11:16:47.682073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d44338d4a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invest_name', sa.String(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('rooms_number', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(precision=2), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invest_name'], ['investments.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flats')
    op.drop_table('investments')
    op.drop_table('developers')
    # ### end Alembic commands ###
